export const cuisineList = [
    "North Indian",
    "South Indian",
    "Chinese",
    "Italian",
    "Mexican",
    "Thai",
    "Japanese",
    "Meals",
    "Fast Foods",
    "Tiffins",
    "Punjabi",
    "Gujarati",
    "Rajasthani",
    "Kerala",
    "American",
    "Korean",
    "French",
    "BBQ",
    "Cafe",
    "Salads",
    "Vegetarian",
    "Gluten-Free",
    "Dairy-Free",
    "Desserts",
    "Pizza",
    "Biryani",
    "Seafood",
    "Street Food",
    "Burgers",
    "Salads",
    "Tandoori",
    "Sushi",
];
  