export const cuisineList = [
    "American",
    "Andhra",
    "BBQ",
    "Biryani",
    "Burgers",
    "Cafe",
    "Chinese",
    "Desserts",
    "Fast Foods",
    "French",
    "Italian",
    "Japanese",
    "Korean",
    "Meals",
    "Mexican",
    "North Indian",
    "Pizza",
    "Punjabi",
    "Salads",
    "Seafood",
    "South Indian",
    "Street Food",
    "Sushi",
    "Tandoori",
    "Tiffins",
    "Vegetarian"
];
  